# --- GENERAL SETTINGS ---
set -g mouse on
set -g base-index 1          # Start windows at 1
setw -g pane-base-index 1     # Start panes at 1
set -g renumber-windows on    # Automatically renumber windows when one is closed

# --- KEYBINDINGS ---
# Set prefix to Ctrl-Space
set -g prefix C-Space
unbind C-b
bind C-Space send-prefix

# Fast toggle between your Shell and Claude windows
bind Space last-window

# Fast reload of conf file
bind r source-file ~/.tmux.conf \; display "Config Reloaded!"

# Tell tmux to use 256-color internally
set -g default-terminal "tmux-256color"

# Enable RGB/TrueColor support for Ghostty (and other modern terminals)
set -as terminal-overrides ",xterm-256color:RGB"

# Enable allow-passthroug so Claude's notification signals reach Ghostty
set -g allow-passthrough on

# --- PLUGINS ---
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'     # Sets focus-events ON
set -g @plugin 'tmux-plugins/tmux-logging'
set -g @plugin 'tmux-plugins/tmux-pain-control' # Sets | and - splits
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'wfxr/tmux-power'

# Automatic restore when tmux starts
set -g @continuum-restore 'on'

# Save Neovim sessions too
set -g @resurrect-strategy-nvim 'session'

# Set the theme for tmux-power (you can choose from 'moon', 'dawn', 'dusk', etc.)
set -g @tmux_power_theme 'everforest'

# --- BOOTSTRAP TPM ---
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && \
   ~/.tmux/plugins/tpm/bin/install_plugins'"

# Initialize TPM (Keep this at the very bottom)
run '~/.tmux/plugins/tpm/tpm'
