#!/bin/bash

set -euo pipefail

if [[ "$(uname -o)" == "Darwin" ]]; then

	# Install Homebrew and packages first
	if [ ! command -v brew ] >/dev/null 2>&1; then
		/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
		echo "Homebrew installed ✅"
	fi

	if [ -f "$HOME/.config/brew/Brewfile" ]; then
		brew bundle --file="$HOME/.config/brew/Brewfile"
		echo "Homebrew packages installed ✅"
	fi

	# Switch to zsh
	if [[ "$SHELL" != *"zsh" ]]; then
		chsh -s $(which zsh)
	fi

	# Install Oh My Zsh
	if [ ! -d "$HOME/.oh-my-zsh" ]; then
		sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
		[[ -f ".zshrc.pre-oh-my-zsh" ]] && mv ".zshrc.pre-oh-my-zsh" ".zshrc"

		# powerlevel10k Theme
		git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

		echo "Oh My Zsh ✅"
	fi

fi

echo "Finished processing bootstrap scripts ✅"
